file(WRITE "launch.json" 
"{\n"
"    \"version\": \"0.2.0\",\n"
"    \"configurations\": [\n"
"        {\n"
"            \"type\": \"lldb\",\n"
"            \"request\": \"launch\",\n"
"            \"name\": \"Debug\",\n"
"            \"program\": \"${workspaceFolder}/Debug/RayLibGame.exe\",\n"
"            \"args\": [],\n"
"            \"cwd\": \"${CMAKE_SOURCE_DIR}\",\n"
"            \"terminal\": \"external\",\n"
"            \"preLaunchTask\": \"CMake: build\"\n"
"        }\n"
"    ]\n"
"}\n"
)
